# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
it:
  languageCode: it-it
  contentDir: content/it
  params:
    description: Comunit√† di chi studia presso il Dipartimento di Informatica - Scienza e Ingegneria dell'Universit di Bologna
    features:
      repository:
        url: "https://github.com/csunibo/csunibo.github.io"
        branch: main
        content_dir: content/it

en:
  languageCode: en-us
  contentDir: content/en
  params:
    description: Community of students from the Department of Computer Science and Engineering of the University of Bologna
    features:
      repository:
        url: "https://github.com/csunibo/csunibo.github.io"
        branch: main
        content_dir: content/en
