# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: L

# SEO

marketing:
  seo:
    site_type: Organization
    local_business_type: ""
    org_name: "CSUnibo"
    description: Comunità di chi studia presso il Dipartimento di Informatica - Scienza e Ingegneria dell'Universit di Bologna
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    google_tag_manager: ""
    microsoft_clarity: ""
  verification:
    google: ""
    baidu: ""

# Site header

header:
  navbar:
    enable: true
    align: r
    show_logo: false
    show_language: true
    show_day_night: true
    show_search: true
    highlight_active_link: false

footer:
  copyright:
    notice: "© {year} CSUnibo. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ""
    disqus:
      shortname: ""
      show_count: true
    commento:
      url: ""
    giscus:
      repo: ""
      repo_id: ""
      category: ""
      category_id: ""
  search:
    provider: wowchemy
    wowchemy:
      min_length: 1
      threshold: 0.3
  map:
    provider: ""
    api_key: ""
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true
